language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip wheel
  - pip install -r tests_requirements.txt
script:
  - py.test tests --cov=peony
cache: pip
after_success:
  - codecov
